<?php
/**
 * DomainApiTest
 * PHP version 8.1
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.<br>You can use https://eu1.unione.io/en/transactional/api/v1 or https://us1.unione.io/en/transactional/api/v1 directly.
 *
 * The version of the OpenAPI document: 1.76
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace UniOne\Test\Api;

use UniOne\Configuration;
use UniOne\ApiException;
use UniOne\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DomainApiTest Class Doc Comment
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DomainApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for domainDelete
     *
     * Deletes a domain. Attention: you should use project's API key to delete a project's domain..
     *
     */
    public function testDomainDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainGetDnsRecords
     *
     * Returns info on domain DNS setup for using with UniOne..
     *
     */
    public function testDomainGetDnsRecords()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainList
     *
     * Returns a list of all registered domains for user or project, together with statuses of last validations..
     *
     */
    public function testDomainList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainValidateDkim
     *
     * Validates DKIM record for domain..
     *
     */
    public function testDomainValidateDkim()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainValidateVerificationRecord
     *
     * Triggers verification record validation for domain..
     *
     */
    public function testDomainValidateVerificationRecord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
