<?php
/**
 * WebhookApiTest
 * PHP version 8.1
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.<br>The preferred way is to use https://api.unione.io/en/transactional/api/v1 endpoint, but also you can use https://eu1.unione.io/en/transactional/api/v1 or https://us1.unione.io/en/transactional/api/v1 directly, depending on the host your account was registered at.
 *
 * The version of the OpenAPI document: 1.76
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace UniOne\Test\Api;

use UniOne\Configuration;
use UniOne\ApiException;
use UniOne\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WebhookApiTest Class Doc Comment
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhookApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for webhookDelete
     *
     * Deletes an event notification handler.
     *
     */
    public function testWebhookDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for webhookGet
     *
     * Gets properties of a [webhook](https://docs.unione.io/en/web-api-ref#webhook)..
     *
     */
    public function testWebhookGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for webhookList
     *
     * List all or some [webhooks](https://docs.unione.io/en/web-api-ref#webhook) (event notification handlers) of a user or a project..
     *
     */
    public function testWebhookList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for webhookSet
     *
     * Sets or edits a [webhook](https://docs.unione.io/en/web-api-ref#webhook), i.e. an event notification handler..
     *
     */
    public function testWebhookSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
