<?php
/**
 * EmailValidationSingle200Response
 *
 * PHP version 8.1
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.<br>You can use https://eu1.unione.io/en/transactional/api/v1 or https://us1.unione.io/en/transactional/api/v1 directly.
 *
 * The version of the OpenAPI document: 1.76
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace UniOne\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use UniOne\ObjectSerializer;

/**
 * EmailValidationSingle200Response Class Doc Comment
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class EmailValidationSingle200Response implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'email_validation_single_200_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'status' => '\UniOne\Model\SuccessStatusString',
        'email' => 'string',
        'result' => 'string',
        'cause' => 'string',
        'validity' => 'int',
        'localPart' => 'string',
        'domain' => 'string',
        'mxFound' => 'bool',
        'mxRecord' => 'string',
        'didYouMean' => 'string',
        'processedAt' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'status' => null,
        'email' => 'email',
        'result' => null,
        'cause' => null,
        'validity' => null,
        'localPart' => null,
        'domain' => null,
        'mxFound' => null,
        'mxRecord' => null,
        'didYouMean' => 'email',
        'processedAt' => 'utc-date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'status' => false,
        'email' => false,
        'result' => false,
        'cause' => false,
        'validity' => false,
        'localPart' => false,
        'domain' => false,
        'mxFound' => false,
        'mxRecord' => false,
        'didYouMean' => false,
        'processedAt' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'status' => 'status',
        'email' => 'email',
        'result' => 'result',
        'cause' => 'cause',
        'validity' => 'validity',
        'localPart' => 'local_part',
        'domain' => 'domain',
        'mxFound' => 'mx_found',
        'mxRecord' => 'mx_record',
        'didYouMean' => 'did_you_mean',
        'processedAt' => 'processed_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'status' => 'setStatus',
        'email' => 'setEmail',
        'result' => 'setResult',
        'cause' => 'setCause',
        'validity' => 'setValidity',
        'localPart' => 'setLocalPart',
        'domain' => 'setDomain',
        'mxFound' => 'setMxFound',
        'mxRecord' => 'setMxRecord',
        'didYouMean' => 'setDidYouMean',
        'processedAt' => 'setProcessedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'status' => 'getStatus',
        'email' => 'getEmail',
        'result' => 'getResult',
        'cause' => 'getCause',
        'validity' => 'getValidity',
        'localPart' => 'getLocalPart',
        'domain' => 'getDomain',
        'mxFound' => 'getMxFound',
        'mxRecord' => 'getMxRecord',
        'didYouMean' => 'getDidYouMean',
        'processedAt' => 'getProcessedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('result', $data ?? [], null);
        $this->setIfExists('cause', $data ?? [], null);
        $this->setIfExists('validity', $data ?? [], null);
        $this->setIfExists('localPart', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('mxFound', $data ?? [], null);
        $this->setIfExists('mxRecord', $data ?? [], null);
        $this->setIfExists('didYouMean', $data ?? [], null);
        $this->setIfExists('processedAt', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['email'] === null) {
            $invalidProperties[] = "'email' can't be null";
        }
        if ($this->container['result'] === null) {
            $invalidProperties[] = "'result' can't be null";
        }
        if ($this->container['cause'] === null) {
            $invalidProperties[] = "'cause' can't be null";
        }
        if ($this->container['validity'] === null) {
            $invalidProperties[] = "'validity' can't be null";
        }
        if ($this->container['localPart'] === null) {
            $invalidProperties[] = "'localPart' can't be null";
        }
        if ($this->container['domain'] === null) {
            $invalidProperties[] = "'domain' can't be null";
        }
        if ($this->container['mxFound'] === null) {
            $invalidProperties[] = "'mxFound' can't be null";
        }
        if ($this->container['mxRecord'] === null) {
            $invalidProperties[] = "'mxRecord' can't be null";
        }
        if ($this->container['didYouMean'] === null) {
            $invalidProperties[] = "'didYouMean' can't be null";
        }
        if ($this->container['processedAt'] === null) {
            $invalidProperties[] = "'processedAt' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets status
     *
     * @return \UniOne\Model\SuccessStatusString
     */
    public function getStatus(): \UniOne\Model\SuccessStatusString
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \UniOne\Model\SuccessStatusString $status status
     *
     * @return $this
     */
    public function setStatus(\UniOne\Model\SuccessStatusString $status): static
    {
        if (is_null($status)) {
            throw new InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail(): string
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email Email address to be checked.
     *
     * @return $this
     */
    public function setEmail(string $email): static
    {
        if (is_null($email)) {
            throw new InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets result
     *
     * @return string
     */
    public function getResult(): string
    {
        return $this->container['result'];
    }

    /**
     * Sets result
     *
     * @param string $result Possible statuses:<br><br>* **valid** - the address is valid,* **invalid** - the address is invalid,* **suspicious** - the address looks suspicious,* **unknown** - could not perform validation, the domain’s mail server has not responded within the time limit.
     *
     * @return $this
     */
    public function setResult(string $result): static
    {
        if (is_null($result)) {
            throw new InvalidArgumentException('non-nullable result cannot be null');
        }
        $this->container['result'] = $result;

        return $this;
    }

    /**
     * Gets cause
     *
     * @return string
     */
    public function getCause(): string
    {
        return $this->container['cause'];
    }

    /**
     * Sets cause
     *
     * @param string $cause Possible statuses:<br><br>* **no_mx_record** - no MX record found for the target domain,* **syntax_error** - the address syntax is invalid,* **possible_typo** - the address is likely to have a typo,* **mailbox_not_found** - the address does not exist,* **global_suppression** - the address has been marked as unreachable due to multiple previous delivery errors,* **disposable** - this is a disposable one-time email address which is usually valid for a few minutes only,* **role** - the address is not likely to belong to an actual person, but rather to a certain business staff role,* **abuse** - the address is known to be a source of a large number of complaints, sometimes issued automatically,* **spamtrap** - this email is a spam trap, it is published openly but never used for actual emails. Sending messages to such addresses has a huge negative impact on reputation score,* **smtp_connection_failed** - the domain’s SMTP server does not respond; the address may contain a typo.
     *
     * @return $this
     */
    public function setCause(string $cause): static
    {
        if (is_null($cause)) {
            throw new InvalidArgumentException('non-nullable cause cannot be null');
        }
        $this->container['cause'] = $cause;

        return $this;
    }

    /**
     * Gets validity
     *
     * @return int
     */
    public function getValidity(): int
    {
        return $this->container['validity'];
    }

    /**
     * Sets validity
     *
     * @param int $validity Validity score, from 0 to 100 (0 – invalid, 100 – valid).
     *
     * @return $this
     */
    public function setValidity(int $validity): static
    {
        if (is_null($validity)) {
            throw new InvalidArgumentException('non-nullable validity cannot be null');
        }
        $this->container['validity'] = $validity;

        return $this;
    }

    /**
     * Gets localPart
     *
     * @return string
     */
    public function getLocalPart(): string
    {
        return $this->container['localPart'];
    }

    /**
     * Sets localPart
     *
     * @param string $localPart Local part (everything preceding the @ sign).
     *
     * @return $this
     */
    public function setLocalPart(string $localPart): static
    {
        if (is_null($localPart)) {
            throw new InvalidArgumentException('non-nullable localPart cannot be null');
        }
        $this->container['localPart'] = $localPart;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string
     */
    public function getDomain(): string
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string $domain Domain name part.
     *
     * @return $this
     */
    public function setDomain(string $domain): static
    {
        if (is_null($domain)) {
            throw new InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets mxFound
     *
     * @return bool
     */
    public function getMxFound(): bool
    {
        return $this->container['mxFound'];
    }

    /**
     * Sets mxFound
     *
     * @param bool $mxFound True if the address’ domain does have an MX record, false if does not.
     *
     * @return $this
     */
    public function setMxFound(bool $mxFound): static
    {
        if (is_null($mxFound)) {
            throw new InvalidArgumentException('non-nullable mxFound cannot be null');
        }
        $this->container['mxFound'] = $mxFound;

        return $this;
    }

    /**
     * Gets mxRecord
     *
     * @return string
     */
    public function getMxRecord(): string
    {
        return $this->container['mxRecord'];
    }

    /**
     * Sets mxRecord
     *
     * @param string $mxRecord Preferred MX record for the domain.
     *
     * @return $this
     */
    public function setMxRecord(string $mxRecord): static
    {
        if (is_null($mxRecord)) {
            throw new InvalidArgumentException('non-nullable mxRecord cannot be null');
        }
        $this->container['mxRecord'] = $mxRecord;

        return $this;
    }

    /**
     * Gets didYouMean
     *
     * @return string
     */
    public function getDidYouMean(): string
    {
        return $this->container['didYouMean'];
    }

    /**
     * Sets didYouMean
     *
     * @param string $didYouMean For addresses which are likely to have typing errors (cause=possible_typo), a suggested variant with a fixed typo.
     *
     * @return $this
     */
    public function setDidYouMean(string $didYouMean): static
    {
        if (is_null($didYouMean)) {
            throw new InvalidArgumentException('non-nullable didYouMean cannot be null');
        }
        $this->container['didYouMean'] = $didYouMean;

        return $this;
    }

    /**
     * Gets processedAt
     *
     * @return string
     */
    public function getProcessedAt(): string
    {
        return $this->container['processedAt'];
    }

    /**
     * Sets processedAt
     *
     * @param string $processedAt Email check date and time, YYYY-MM-DD hh:mm:ss UTC.
     *
     * @return $this
     */
    public function setProcessedAt(string $processedAt): static
    {
        if (is_null($processedAt)) {
            throw new InvalidArgumentException('non-nullable processedAt cannot be null');
        }
        $this->container['processedAt'] = $processedAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


