<?php
/**
 * EventDumpCreateRequest
 *
 * PHP version 8.1
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.<br>You can use https://eu1.unione.io/en/transactional/api/v1 or https://us1.unione.io/en/transactional/api/v1 directly.
 *
 * The version of the OpenAPI document: 1.76
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace UniOne\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use UniOne\ObjectSerializer;

/**
 * EventDumpCreateRequest Class Doc Comment
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class EventDumpCreateRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'event_dump_create_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'startTime' => 'string',
        'endTime' => 'string',
        'limit' => 'int',
        'allProjects' => 'bool',
        'filter' => '\UniOne\Model\FilterObject',
        'dumpFields' => 'string[]',
        'aggregate' => 'string',
        'delimiter' => 'string',
        'format' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'startTime' => 'utc-date-time',
        'endTime' => 'utc-date-time',
        'limit' => null,
        'allProjects' => null,
        'filter' => null,
        'dumpFields' => null,
        'aggregate' => null,
        'delimiter' => null,
        'format' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'startTime' => false,
        'endTime' => false,
        'limit' => false,
        'allProjects' => false,
        'filter' => false,
        'dumpFields' => false,
        'aggregate' => false,
        'delimiter' => false,
        'format' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'startTime' => 'start_time',
        'endTime' => 'end_time',
        'limit' => 'limit',
        'allProjects' => 'all_projects',
        'filter' => 'filter',
        'dumpFields' => 'dump_fields',
        'aggregate' => 'aggregate',
        'delimiter' => 'delimiter',
        'format' => 'format'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'startTime' => 'setStartTime',
        'endTime' => 'setEndTime',
        'limit' => 'setLimit',
        'allProjects' => 'setAllProjects',
        'filter' => 'setFilter',
        'dumpFields' => 'setDumpFields',
        'aggregate' => 'setAggregate',
        'delimiter' => 'setDelimiter',
        'format' => 'setFormat'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'startTime' => 'getStartTime',
        'endTime' => 'getEndTime',
        'limit' => 'getLimit',
        'allProjects' => 'getAllProjects',
        'filter' => 'getFilter',
        'dumpFields' => 'getDumpFields',
        'aggregate' => 'getAggregate',
        'delimiter' => 'getDelimiter',
        'format' => 'getFormat'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('startTime', $data ?? [], null);
        $this->setIfExists('endTime', $data ?? [], null);
        $this->setIfExists('limit', $data ?? [], null);
        $this->setIfExists('allProjects', $data ?? [], false);
        $this->setIfExists('filter', $data ?? [], null);
        $this->setIfExists('dumpFields', $data ?? [], null);
        $this->setIfExists('aggregate', $data ?? [], null);
        $this->setIfExists('delimiter', $data ?? [], null);
        $this->setIfExists('format', $data ?? [], 'csv');
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['startTime'] === null) {
            $invalidProperties[] = "'startTime' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets startTime
     *
     * @return string
     */
    public function getStartTime(): string
    {
        return $this->container['startTime'];
    }

    /**
     * Sets startTime
     *
     * @param string $startTime Date and time in YYYY-MM-DD hh:mm:ss format, specifying period start time. Data is stored for up to 32 days, depending on your tariff.
     *
     * @return $this
     */
    public function setStartTime(string $startTime): static
    {
        if (is_null($startTime)) {
            throw new InvalidArgumentException('non-nullable startTime cannot be null');
        }
        $this->container['startTime'] = $startTime;

        return $this;
    }

    /**
     * Gets endTime
     *
     * @return string|null
     */
    public function getEndTime(): ?string
    {
        return $this->container['endTime'];
    }

    /**
     * Sets endTime
     *
     * @param string|null $endTime Date and time in YYYY-MM-DD hh:mm:ss format, specifying period end time (non-inclusive).
     *
     * @return $this
     */
    public function setEndTime(?string $endTime): static
    {
        if (is_null($endTime)) {
            throw new InvalidArgumentException('non-nullable endTime cannot be null');
        }
        $this->container['endTime'] = $endTime;

        return $this;
    }

    /**
     * Gets limit
     *
     * @return int|null
     */
    public function getLimit(): ?int
    {
        return $this->container['limit'];
    }

    /**
     * Sets limit
     *
     * @param int|null $limit Maximum number of events returned (default is 50). If this value is over 100 000, several files will be created, each having 100 000 events maximum.
     *
     * @return $this
     */
    public function setLimit(?int $limit): static
    {
        if (is_null($limit)) {
            throw new InvalidArgumentException('non-nullable limit cannot be null');
        }
        $this->container['limit'] = $limit;

        return $this;
    }

    /**
     * Gets allProjects
     *
     * @return bool|null
     */
    public function getAllProjects(): ?bool
    {
        return $this->container['allProjects'];
    }

    /**
     * Sets allProjects
     *
     * @param bool|null $allProjects For accounts with projects enabled, the value all_projects=true allows to fetch data for all existing projects.
     *
     * @return $this
     */
    public function setAllProjects(?bool $allProjects): static
    {
        if (is_null($allProjects)) {
            throw new InvalidArgumentException('non-nullable allProjects cannot be null');
        }
        $this->container['allProjects'] = $allProjects;

        return $this;
    }

    /**
     * Gets filter
     *
     * @return \UniOne\Model\FilterObject|null
     */
    public function getFilter(): ?\UniOne\Model\FilterObject
    {
        return $this->container['filter'];
    }

    /**
     * Sets filter
     *
     * @param \UniOne\Model\FilterObject|null $filter filter
     *
     * @return $this
     */
    public function setFilter(?\UniOne\Model\FilterObject $filter): static
    {
        if (is_null($filter)) {
            throw new InvalidArgumentException('non-nullable filter cannot be null');
        }
        $this->container['filter'] = $filter;

        return $this;
    }

    /**
     * Gets dumpFields
     *
     * @return string[]|null
     */
    public function getDumpFields(): ?array
    {
        return $this->container['dumpFields'];
    }

    /**
     * Sets dumpFields
     *
     * @param string[]|null $dumpFields An array of strings containing the names of columns you need in your report, in your preferred order. If the 'dump_fields' array is missing or empty, a default field list and order will be applied. Allowed values, in their default order, are - 'project_id', 'event_time', 'job_id', 'from_email', 'email', 'status', 'delivery_status', 'metadata', 'destination_response', 'user_agent', 'url', 'ip', 'tags'. For maximum security, the 'subject' field is not included by default, but you can add it by explicitly including in the 'dump_fields' array.
     *
     * @return $this
     */
    public function setDumpFields(?array $dumpFields): static
    {
        if (is_null($dumpFields)) {
            throw new InvalidArgumentException('non-nullable dumpFields cannot be null');
        }
        $this->container['dumpFields'] = $dumpFields;

        return $this;
    }

    /**
     * Gets aggregate
     *
     * @return string|null
     */
    public function getAggregate(): ?string
    {
        return $this->container['aggregate'];
    }

    /**
     * Sets aggregate
     *
     * @param string|null $aggregate Allows you to obtain aggregated statistics for a given time period. The two allowed values are:<br><br>* __day_status__ - fetch aggregated statistics (the filter value must be missing or empty, as filters are not allowed with this option);* __an empty string__ - used by default, event_dump/create works as if the aggregate parameter is omitted.
     *
     * @return $this
     */
    public function setAggregate(?string $aggregate): static
    {
        if (is_null($aggregate)) {
            throw new InvalidArgumentException('non-nullable aggregate cannot be null');
        }
        $this->container['aggregate'] = $aggregate;

        return $this;
    }

    /**
     * Gets delimiter
     *
     * @return string|null
     */
    public function getDelimiter(): ?string
    {
        return $this->container['delimiter'];
    }

    /**
     * Sets delimiter
     *
     * @param string|null $delimiter Field delimiter, can be set to either ',' or ';', defaults to ','.
     *
     * @return $this
     */
    public function setDelimiter(?string $delimiter): static
    {
        if (is_null($delimiter)) {
            throw new InvalidArgumentException('non-nullable delimiter cannot be null');
        }
        $this->container['delimiter'] = $delimiter;

        return $this;
    }

    /**
     * Gets format
     *
     * @return string|null
     */
    public function getFormat(): ?string
    {
        return $this->container['format'];
    }

    /**
     * Sets format
     *
     * @param string|null $format File format, either “csv” (default) or “csv_gzip”.
     *
     * @return $this
     */
    public function setFormat(?string $format): static
    {
        if (is_null($format)) {
            throw new InvalidArgumentException('non-nullable format cannot be null');
        }
        $this->container['format'] = $format;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


