<?php
/**
 * TemplateEngineString
 *
 * PHP version 8.1
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.<br>You can use https://eu1.unione.io/en/transactional/api/v1 or https://us1.unione.io/en/transactional/api/v1 directly.
 *
 * The version of the OpenAPI document: 1.76
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace UniOne\Model;

/**
 * TemplateEngineString Class Doc Comment
 *
 * @description The [template engine](https://docs.unione.io/en/template-engines) for handling the substitutions(merge tags), **simple**, **velocity**, **liquid** or **none**. Default value is **simple**.
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum TemplateEngineString: string
{
    case SIMPLE = 'simple';

    case VELOCITY = 'velocity';

    case LIQUID = 'liquid';

    case NONE = 'none';

    case UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';
}


