<?php
/**
 * WebhookObject
 *
 * PHP version 8.1
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.<br>You can use https://eu1.unione.io/en/transactional/api/v1 or https://us1.unione.io/en/transactional/api/v1 directly.
 *
 * The version of the OpenAPI document: 1.76
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace UniOne\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use UniOne\ObjectSerializer;

/**
 * WebhookObject Class Doc Comment
 *
 * @description Object with all the webhook properties.
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class WebhookObject implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'WebhookObject';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'int',
        'url' => 'string',
        'status' => '\UniOne\Model\WebhookStatusString',
        'eventFormat' => '\UniOne\Model\WebhookEventFormatString',
        'deliveryInfo' => '\UniOne\Model\WebhookDeliveryInfoInteger',
        'singleEvent' => '\UniOne\Model\WebhookSingleEventInteger',
        'maxParallel' => 'int',
        'updatedAt' => 'string',
        'events' => '\UniOne\Model\WebhookEventsObject'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => null,
        'url' => 'uri',
        'status' => null,
        'eventFormat' => null,
        'deliveryInfo' => null,
        'singleEvent' => null,
        'maxParallel' => null,
        'updatedAt' => 'utc-date-time',
        'events' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => false,
        'url' => false,
        'status' => false,
        'eventFormat' => false,
        'deliveryInfo' => false,
        'singleEvent' => false,
        'maxParallel' => false,
        'updatedAt' => false,
        'events' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'url' => 'url',
        'status' => 'status',
        'eventFormat' => 'event_format',
        'deliveryInfo' => 'delivery_info',
        'singleEvent' => 'single_event',
        'maxParallel' => 'max_parallel',
        'updatedAt' => 'updated_at',
        'events' => 'events'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'url' => 'setUrl',
        'status' => 'setStatus',
        'eventFormat' => 'setEventFormat',
        'deliveryInfo' => 'setDeliveryInfo',
        'singleEvent' => 'setSingleEvent',
        'maxParallel' => 'setMaxParallel',
        'updatedAt' => 'setUpdatedAt',
        'events' => 'setEvents'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'url' => 'getUrl',
        'status' => 'getStatus',
        'eventFormat' => 'getEventFormat',
        'deliveryInfo' => 'getDeliveryInfo',
        'singleEvent' => 'getSingleEvent',
        'maxParallel' => 'getMaxParallel',
        'updatedAt' => 'getUpdatedAt',
        'events' => 'getEvents'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('eventFormat', $data ?? [], null);
        $this->setIfExists('deliveryInfo', $data ?? [], null);
        $this->setIfExists('singleEvent', $data ?? [], null);
        $this->setIfExists('maxParallel', $data ?? [], 10);
        $this->setIfExists('updatedAt', $data ?? [], null);
        $this->setIfExists('events', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['eventFormat'] === null) {
            $invalidProperties[] = "'eventFormat' can't be null";
        }
        if ($this->container['deliveryInfo'] === null) {
            $invalidProperties[] = "'deliveryInfo' can't be null";
        }
        if ($this->container['singleEvent'] === null) {
            $invalidProperties[] = "'singleEvent' can't be null";
        }
        if ($this->container['maxParallel'] === null) {
            $invalidProperties[] = "'maxParallel' can't be null";
        }
        if (($this->container['maxParallel'] > 100)) {
            $invalidProperties[] = "invalid value for 'maxParallel', must be smaller than or equal to 100.";
        }

        if (($this->container['maxParallel'] < 5)) {
            $invalidProperties[] = "invalid value for 'maxParallel', must be bigger than or equal to 5.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId(): int
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id Webhook unique identifier.
     *
     * @return $this
     */
    public function setId(int $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl(): string
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url Webhook URL.
     *
     * @return $this
     */
    public function setUrl(string $url): static
    {
        if (is_null($url)) {
            throw new InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \UniOne\Model\WebhookStatusString
     */
    public function getStatus(): \UniOne\Model\WebhookStatusString
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \UniOne\Model\WebhookStatusString $status status
     *
     * @return $this
     */
    public function setStatus(\UniOne\Model\WebhookStatusString $status): static
    {
        if (is_null($status)) {
            throw new InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets eventFormat
     *
     * @return \UniOne\Model\WebhookEventFormatString
     */
    public function getEventFormat(): \UniOne\Model\WebhookEventFormatString
    {
        return $this->container['eventFormat'];
    }

    /**
     * Sets eventFormat
     *
     * @param \UniOne\Model\WebhookEventFormatString $eventFormat eventFormat
     *
     * @return $this
     */
    public function setEventFormat(\UniOne\Model\WebhookEventFormatString $eventFormat): static
    {
        if (is_null($eventFormat)) {
            throw new InvalidArgumentException('non-nullable eventFormat cannot be null');
        }
        $this->container['eventFormat'] = $eventFormat;

        return $this;
    }

    /**
     * Gets deliveryInfo
     *
     * @return \UniOne\Model\WebhookDeliveryInfoInteger
     */
    public function getDeliveryInfo(): \UniOne\Model\WebhookDeliveryInfoInteger
    {
        return $this->container['deliveryInfo'];
    }

    /**
     * Sets deliveryInfo
     *
     * @param \UniOne\Model\WebhookDeliveryInfoInteger $deliveryInfo deliveryInfo
     *
     * @return $this
     */
    public function setDeliveryInfo(\UniOne\Model\WebhookDeliveryInfoInteger $deliveryInfo): static
    {
        if (is_null($deliveryInfo)) {
            throw new InvalidArgumentException('non-nullable deliveryInfo cannot be null');
        }
        $this->container['deliveryInfo'] = $deliveryInfo;

        return $this;
    }

    /**
     * Gets singleEvent
     *
     * @return \UniOne\Model\WebhookSingleEventInteger
     */
    public function getSingleEvent(): \UniOne\Model\WebhookSingleEventInteger
    {
        return $this->container['singleEvent'];
    }

    /**
     * Sets singleEvent
     *
     * @param \UniOne\Model\WebhookSingleEventInteger $singleEvent singleEvent
     *
     * @return $this
     */
    public function setSingleEvent(\UniOne\Model\WebhookSingleEventInteger $singleEvent): static
    {
        if (is_null($singleEvent)) {
            throw new InvalidArgumentException('non-nullable singleEvent cannot be null');
        }
        $this->container['singleEvent'] = $singleEvent;

        return $this;
    }

    /**
     * Gets maxParallel
     *
     * @return int
     */
    public function getMaxParallel(): int
    {
        return $this->container['maxParallel'];
    }

    /**
     * Sets maxParallel
     *
     * @param int $maxParallel Maximum quantity of permitted parallel queries to your server. The more your server can handle - the better.
     *
     * @return $this
     */
    public function setMaxParallel(int $maxParallel): static
    {
        if (is_null($maxParallel)) {
            throw new InvalidArgumentException('non-nullable maxParallel cannot be null');
        }

        if (($maxParallel > 100)) {
            throw new InvalidArgumentException('invalid value for $maxParallel when calling WebhookObject., must be smaller than or equal to 100.');
        }
        if (($maxParallel < 5)) {
            throw new InvalidArgumentException('invalid value for $maxParallel when calling WebhookObject., must be bigger than or equal to 5.');
        }

        $this->container['maxParallel'] = $maxParallel;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return string|null
     */
    public function getUpdatedAt(): ?string
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param string|null $updatedAt Webhook properties last update date and time in UTC timezone in **YYYY-MM-DD hh:mm:ss** format.
     *
     * @return $this
     */
    public function setUpdatedAt(?string $updatedAt): static
    {
        if (is_null($updatedAt)) {
            throw new InvalidArgumentException('non-nullable updatedAt cannot be null');
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }

    /**
     * Gets events
     *
     * @return \UniOne\Model\WebhookEventsObject|null
     */
    public function getEvents(): ?\UniOne\Model\WebhookEventsObject
    {
        return $this->container['events'];
    }

    /**
     * Sets events
     *
     * @param \UniOne\Model\WebhookEventsObject|null $events events
     *
     * @return $this
     */
    public function setEvents(?\UniOne\Model\WebhookEventsObject $events): static
    {
        if (is_null($events)) {
            throw new InvalidArgumentException('non-nullable events cannot be null');
        }
        $this->container['events'] = $events;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


