<?php
/**
 * DomainApi
 * PHP version 8.1
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.<br>You can use https://eu1.unione.io/en/transactional/api/v1 or https://us1.unione.io/en/transactional/api/v1 directly.
 *
 * The version of the OpenAPI document: 1.76
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace UniOne\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use UniOne\ApiException;
use UniOne\Configuration;
use UniOne\HeaderSelector;
use UniOne\FormDataProcessor;
use UniOne\ObjectSerializer;

/**
 * DomainApi Class Doc Comment
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DomainApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'domainDelete' => [
            'application/json',
        ],
        'domainGetDnsRecords' => [
            'application/json',
        ],
        'domainList' => [
            'application/json',
        ],
        'domainValidateDkim' => [
            'application/json',
        ],
        'domainValidateVerificationRecord' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation domainDelete
     *
     * Deletes a domain. Attention: you should use project&#39;s API key to delete a project&#39;s domain.
     *
     * @param  \UniOne\Model\DomainDeleteRequest $domainDeleteRequest domainDeleteRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \UniOne\Model\DomainDelete200Response|\UniOne\Model\ErrorResponse
     */
    public function domainDelete(
        \UniOne\Model\DomainDeleteRequest $domainDeleteRequest,
        string $contentType = self::contentTypes['domainDelete'][0]
    ): \UniOne\Model\DomainDelete200Response|\UniOne\Model\ErrorResponse
    {
        list($response) = $this->domainDeleteWithHttpInfo($domainDeleteRequest, $contentType);
        return $response;
    }

    /**
     * Operation domainDeleteWithHttpInfo
     *
     * Deletes a domain. Attention: you should use project&#39;s API key to delete a project&#39;s domain.
     *
     * @param  \UniOne\Model\DomainDeleteRequest $domainDeleteRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \UniOne\Model\DomainDelete200Response|\UniOne\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function domainDeleteWithHttpInfo(
        \UniOne\Model\DomainDeleteRequest $domainDeleteRequest,
        string $contentType = self::contentTypes['domainDelete'][0]
    ): array
    {
        $request = $this->domainDeleteRequest($domainDeleteRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\DomainDelete200Response',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\UniOne\Model\DomainDelete200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\DomainDelete200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation domainDeleteAsync
     *
     * Deletes a domain. Attention: you should use project&#39;s API key to delete a project&#39;s domain.
     *
     * @param  \UniOne\Model\DomainDeleteRequest $domainDeleteRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function domainDeleteAsync(
        \UniOne\Model\DomainDeleteRequest $domainDeleteRequest,
        string $contentType = self::contentTypes['domainDelete'][0]
    ): PromiseInterface
    {
        return $this->domainDeleteAsyncWithHttpInfo($domainDeleteRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation domainDeleteAsyncWithHttpInfo
     *
     * Deletes a domain. Attention: you should use project&#39;s API key to delete a project&#39;s domain.
     *
     * @param  \UniOne\Model\DomainDeleteRequest $domainDeleteRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function domainDeleteAsyncWithHttpInfo(
        \UniOne\Model\DomainDeleteRequest $domainDeleteRequest,
        string $contentType = self::contentTypes['domainDelete'][0]
    ): PromiseInterface
    {
        $returnType = '\UniOne\Model\DomainDelete200Response';
        $request = $this->domainDeleteRequest($domainDeleteRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'domainDelete'
     *
     * @param  \UniOne\Model\DomainDeleteRequest $domainDeleteRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function domainDeleteRequest(
        \UniOne\Model\DomainDeleteRequest $domainDeleteRequest,
        string $contentType = self::contentTypes['domainDelete'][0]
    ): Request
    {

        // verify the required parameter 'domainDeleteRequest' is set
        if ($domainDeleteRequest === null || (is_array($domainDeleteRequest) && count($domainDeleteRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $domainDeleteRequest when calling domainDelete'
            );
        }


        $resourcePath = '/domain/delete.json';
        $formParams = [];
        $queryParams = [
            'platform' => 'php8-sdk'
        ];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($domainDeleteRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($domainDeleteRequest));
            } else {
                $httpBody = $domainDeleteRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation domainGetDnsRecords
     *
     * Returns info on domain DNS setup for using with UniOne.
     *
     * @param  \UniOne\Model\DomainGetDnsRecordsRequest $domainGetDnsRecordsRequest domainGetDnsRecordsRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainGetDnsRecords'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \UniOne\Model\DomainGetDnsRecords200Response|\UniOne\Model\ErrorResponse
     */
    public function domainGetDnsRecords(
        \UniOne\Model\DomainGetDnsRecordsRequest $domainGetDnsRecordsRequest,
        string $contentType = self::contentTypes['domainGetDnsRecords'][0]
    ): \UniOne\Model\DomainGetDnsRecords200Response|\UniOne\Model\ErrorResponse
    {
        list($response) = $this->domainGetDnsRecordsWithHttpInfo($domainGetDnsRecordsRequest, $contentType);
        return $response;
    }

    /**
     * Operation domainGetDnsRecordsWithHttpInfo
     *
     * Returns info on domain DNS setup for using with UniOne.
     *
     * @param  \UniOne\Model\DomainGetDnsRecordsRequest $domainGetDnsRecordsRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainGetDnsRecords'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \UniOne\Model\DomainGetDnsRecords200Response|\UniOne\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function domainGetDnsRecordsWithHttpInfo(
        \UniOne\Model\DomainGetDnsRecordsRequest $domainGetDnsRecordsRequest,
        string $contentType = self::contentTypes['domainGetDnsRecords'][0]
    ): array
    {
        $request = $this->domainGetDnsRecordsRequest($domainGetDnsRecordsRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\DomainGetDnsRecords200Response',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\UniOne\Model\DomainGetDnsRecords200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\DomainGetDnsRecords200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation domainGetDnsRecordsAsync
     *
     * Returns info on domain DNS setup for using with UniOne.
     *
     * @param  \UniOne\Model\DomainGetDnsRecordsRequest $domainGetDnsRecordsRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainGetDnsRecords'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function domainGetDnsRecordsAsync(
        \UniOne\Model\DomainGetDnsRecordsRequest $domainGetDnsRecordsRequest,
        string $contentType = self::contentTypes['domainGetDnsRecords'][0]
    ): PromiseInterface
    {
        return $this->domainGetDnsRecordsAsyncWithHttpInfo($domainGetDnsRecordsRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation domainGetDnsRecordsAsyncWithHttpInfo
     *
     * Returns info on domain DNS setup for using with UniOne.
     *
     * @param  \UniOne\Model\DomainGetDnsRecordsRequest $domainGetDnsRecordsRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainGetDnsRecords'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function domainGetDnsRecordsAsyncWithHttpInfo(
        \UniOne\Model\DomainGetDnsRecordsRequest $domainGetDnsRecordsRequest,
        string $contentType = self::contentTypes['domainGetDnsRecords'][0]
    ): PromiseInterface
    {
        $returnType = '\UniOne\Model\DomainGetDnsRecords200Response';
        $request = $this->domainGetDnsRecordsRequest($domainGetDnsRecordsRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'domainGetDnsRecords'
     *
     * @param  \UniOne\Model\DomainGetDnsRecordsRequest $domainGetDnsRecordsRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainGetDnsRecords'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function domainGetDnsRecordsRequest(
        \UniOne\Model\DomainGetDnsRecordsRequest $domainGetDnsRecordsRequest,
        string $contentType = self::contentTypes['domainGetDnsRecords'][0]
    ): Request
    {

        // verify the required parameter 'domainGetDnsRecordsRequest' is set
        if ($domainGetDnsRecordsRequest === null || (is_array($domainGetDnsRecordsRequest) && count($domainGetDnsRecordsRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $domainGetDnsRecordsRequest when calling domainGetDnsRecords'
            );
        }


        $resourcePath = '/domain/get-dns-records.json';
        $formParams = [];
        $queryParams = [
            'platform' => 'php8-sdk'
        ];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($domainGetDnsRecordsRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($domainGetDnsRecordsRequest));
            } else {
                $httpBody = $domainGetDnsRecordsRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation domainList
     *
     * Returns a list of all registered domains for user or project, together with statuses of last validations.
     *
     * @param  \UniOne\Model\DomainListRequest $domainListRequest domainListRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainList'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \UniOne\Model\DomainList200Response|\UniOne\Model\ErrorResponse
     */
    public function domainList(
        \UniOne\Model\DomainListRequest $domainListRequest,
        string $contentType = self::contentTypes['domainList'][0]
    ): \UniOne\Model\DomainList200Response|\UniOne\Model\ErrorResponse
    {
        list($response) = $this->domainListWithHttpInfo($domainListRequest, $contentType);
        return $response;
    }

    /**
     * Operation domainListWithHttpInfo
     *
     * Returns a list of all registered domains for user or project, together with statuses of last validations.
     *
     * @param  \UniOne\Model\DomainListRequest $domainListRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainList'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \UniOne\Model\DomainList200Response|\UniOne\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function domainListWithHttpInfo(
        \UniOne\Model\DomainListRequest $domainListRequest,
        string $contentType = self::contentTypes['domainList'][0]
    ): array
    {
        $request = $this->domainListRequest($domainListRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\DomainList200Response',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\UniOne\Model\DomainList200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\DomainList200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation domainListAsync
     *
     * Returns a list of all registered domains for user or project, together with statuses of last validations.
     *
     * @param  \UniOne\Model\DomainListRequest $domainListRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainList'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function domainListAsync(
        \UniOne\Model\DomainListRequest $domainListRequest,
        string $contentType = self::contentTypes['domainList'][0]
    ): PromiseInterface
    {
        return $this->domainListAsyncWithHttpInfo($domainListRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation domainListAsyncWithHttpInfo
     *
     * Returns a list of all registered domains for user or project, together with statuses of last validations.
     *
     * @param  \UniOne\Model\DomainListRequest $domainListRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainList'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function domainListAsyncWithHttpInfo(
        \UniOne\Model\DomainListRequest $domainListRequest,
        string $contentType = self::contentTypes['domainList'][0]
    ): PromiseInterface
    {
        $returnType = '\UniOne\Model\DomainList200Response';
        $request = $this->domainListRequest($domainListRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'domainList'
     *
     * @param  \UniOne\Model\DomainListRequest $domainListRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainList'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function domainListRequest(
        \UniOne\Model\DomainListRequest $domainListRequest,
        string $contentType = self::contentTypes['domainList'][0]
    ): Request
    {

        // verify the required parameter 'domainListRequest' is set
        if ($domainListRequest === null || (is_array($domainListRequest) && count($domainListRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $domainListRequest when calling domainList'
            );
        }


        $resourcePath = '/domain/list.json';
        $formParams = [];
        $queryParams = [
            'platform' => 'php8-sdk'
        ];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($domainListRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($domainListRequest));
            } else {
                $httpBody = $domainListRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation domainValidateDkim
     *
     * Validates DKIM record for domain.
     *
     * @param  \UniOne\Model\DomainValidateDkimRequest $domainValidateDkimRequest domainValidateDkimRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainValidateDkim'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \UniOne\Model\DomainValidateVerificationRecord200Response|\UniOne\Model\ErrorResponse
     */
    public function domainValidateDkim(
        \UniOne\Model\DomainValidateDkimRequest $domainValidateDkimRequest,
        string $contentType = self::contentTypes['domainValidateDkim'][0]
    ): \UniOne\Model\DomainValidateVerificationRecord200Response|\UniOne\Model\ErrorResponse
    {
        list($response) = $this->domainValidateDkimWithHttpInfo($domainValidateDkimRequest, $contentType);
        return $response;
    }

    /**
     * Operation domainValidateDkimWithHttpInfo
     *
     * Validates DKIM record for domain.
     *
     * @param  \UniOne\Model\DomainValidateDkimRequest $domainValidateDkimRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainValidateDkim'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \UniOne\Model\DomainValidateVerificationRecord200Response|\UniOne\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function domainValidateDkimWithHttpInfo(
        \UniOne\Model\DomainValidateDkimRequest $domainValidateDkimRequest,
        string $contentType = self::contentTypes['domainValidateDkim'][0]
    ): array
    {
        $request = $this->domainValidateDkimRequest($domainValidateDkimRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\DomainValidateVerificationRecord200Response',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\UniOne\Model\DomainValidateVerificationRecord200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\DomainValidateVerificationRecord200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation domainValidateDkimAsync
     *
     * Validates DKIM record for domain.
     *
     * @param  \UniOne\Model\DomainValidateDkimRequest $domainValidateDkimRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainValidateDkim'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function domainValidateDkimAsync(
        \UniOne\Model\DomainValidateDkimRequest $domainValidateDkimRequest,
        string $contentType = self::contentTypes['domainValidateDkim'][0]
    ): PromiseInterface
    {
        return $this->domainValidateDkimAsyncWithHttpInfo($domainValidateDkimRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation domainValidateDkimAsyncWithHttpInfo
     *
     * Validates DKIM record for domain.
     *
     * @param  \UniOne\Model\DomainValidateDkimRequest $domainValidateDkimRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainValidateDkim'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function domainValidateDkimAsyncWithHttpInfo(
        \UniOne\Model\DomainValidateDkimRequest $domainValidateDkimRequest,
        string $contentType = self::contentTypes['domainValidateDkim'][0]
    ): PromiseInterface
    {
        $returnType = '\UniOne\Model\DomainValidateVerificationRecord200Response';
        $request = $this->domainValidateDkimRequest($domainValidateDkimRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'domainValidateDkim'
     *
     * @param  \UniOne\Model\DomainValidateDkimRequest $domainValidateDkimRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainValidateDkim'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function domainValidateDkimRequest(
        \UniOne\Model\DomainValidateDkimRequest $domainValidateDkimRequest,
        string $contentType = self::contentTypes['domainValidateDkim'][0]
    ): Request
    {

        // verify the required parameter 'domainValidateDkimRequest' is set
        if ($domainValidateDkimRequest === null || (is_array($domainValidateDkimRequest) && count($domainValidateDkimRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $domainValidateDkimRequest when calling domainValidateDkim'
            );
        }


        $resourcePath = '/domain/validate-dkim.json';
        $formParams = [];
        $queryParams = [
            'platform' => 'php8-sdk'
        ];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($domainValidateDkimRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($domainValidateDkimRequest));
            } else {
                $httpBody = $domainValidateDkimRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation domainValidateVerificationRecord
     *
     * Triggers verification record validation for domain.
     *
     * @param  \UniOne\Model\DomainValidateVerificationRecordRequest $domainValidateVerificationRecordRequest domainValidateVerificationRecordRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainValidateVerificationRecord'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \UniOne\Model\DomainValidateVerificationRecord200Response|\UniOne\Model\ErrorResponse
     */
    public function domainValidateVerificationRecord(
        \UniOne\Model\DomainValidateVerificationRecordRequest $domainValidateVerificationRecordRequest,
        string $contentType = self::contentTypes['domainValidateVerificationRecord'][0]
    ): \UniOne\Model\DomainValidateVerificationRecord200Response|\UniOne\Model\ErrorResponse
    {
        list($response) = $this->domainValidateVerificationRecordWithHttpInfo($domainValidateVerificationRecordRequest, $contentType);
        return $response;
    }

    /**
     * Operation domainValidateVerificationRecordWithHttpInfo
     *
     * Triggers verification record validation for domain.
     *
     * @param  \UniOne\Model\DomainValidateVerificationRecordRequest $domainValidateVerificationRecordRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainValidateVerificationRecord'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \UniOne\Model\DomainValidateVerificationRecord200Response|\UniOne\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function domainValidateVerificationRecordWithHttpInfo(
        \UniOne\Model\DomainValidateVerificationRecordRequest $domainValidateVerificationRecordRequest,
        string $contentType = self::contentTypes['domainValidateVerificationRecord'][0]
    ): array
    {
        $request = $this->domainValidateVerificationRecordRequest($domainValidateVerificationRecordRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\DomainValidateVerificationRecord200Response',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\UniOne\Model\DomainValidateVerificationRecord200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\DomainValidateVerificationRecord200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation domainValidateVerificationRecordAsync
     *
     * Triggers verification record validation for domain.
     *
     * @param  \UniOne\Model\DomainValidateVerificationRecordRequest $domainValidateVerificationRecordRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainValidateVerificationRecord'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function domainValidateVerificationRecordAsync(
        \UniOne\Model\DomainValidateVerificationRecordRequest $domainValidateVerificationRecordRequest,
        string $contentType = self::contentTypes['domainValidateVerificationRecord'][0]
    ): PromiseInterface
    {
        return $this->domainValidateVerificationRecordAsyncWithHttpInfo($domainValidateVerificationRecordRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation domainValidateVerificationRecordAsyncWithHttpInfo
     *
     * Triggers verification record validation for domain.
     *
     * @param  \UniOne\Model\DomainValidateVerificationRecordRequest $domainValidateVerificationRecordRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainValidateVerificationRecord'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function domainValidateVerificationRecordAsyncWithHttpInfo(
        \UniOne\Model\DomainValidateVerificationRecordRequest $domainValidateVerificationRecordRequest,
        string $contentType = self::contentTypes['domainValidateVerificationRecord'][0]
    ): PromiseInterface
    {
        $returnType = '\UniOne\Model\DomainValidateVerificationRecord200Response';
        $request = $this->domainValidateVerificationRecordRequest($domainValidateVerificationRecordRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'domainValidateVerificationRecord'
     *
     * @param  \UniOne\Model\DomainValidateVerificationRecordRequest $domainValidateVerificationRecordRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['domainValidateVerificationRecord'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function domainValidateVerificationRecordRequest(
        \UniOne\Model\DomainValidateVerificationRecordRequest $domainValidateVerificationRecordRequest,
        string $contentType = self::contentTypes['domainValidateVerificationRecord'][0]
    ): Request
    {

        // verify the required parameter 'domainValidateVerificationRecordRequest' is set
        if ($domainValidateVerificationRecordRequest === null || (is_array($domainValidateVerificationRecordRequest) && count($domainValidateVerificationRecordRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $domainValidateVerificationRecordRequest when calling domainValidateVerificationRecord'
            );
        }


        $resourcePath = '/domain/validate-verification-record.json';
        $formParams = [];
        $queryParams = [
            'platform' => 'php8-sdk'
        ];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($domainValidateVerificationRecordRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($domainValidateVerificationRecordRequest));
            } else {
                $httpBody = $domainValidateVerificationRecordRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
