<?php
/**
 * SuppressionApi
 * PHP version 8.1
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.<br>The preferred way is to use https://api.unione.io/en/transactional/api/v1 endpoint, but also you can use https://eu1.unione.io/en/transactional/api/v1 or https://us1.unione.io/en/transactional/api/v1 directly, depending on the host your account was registered at.
 *
 * The version of the OpenAPI document: 1.76
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace UniOne\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use UniOne\ApiException;
use UniOne\Configuration;
use UniOne\HeaderSelector;
use UniOne\FormDataProcessor;
use UniOne\ObjectSerializer;

/**
 * SuppressionApi Class Doc Comment
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SuppressionApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'suppressionDelete' => [
            'application/json',
        ],
        'suppressionGet' => [
            'application/json',
        ],
        'suppressionList' => [
            'application/json',
        ],
        'suppressionSet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation suppressionDelete
     *
     * Deletes an email from suppression list (only records with is_deletable&#x3D;true). If there are no entries of this email in the suppression list, API error 3003 is returned. If such entries exist but no one can be deleted, API error 3004 is returned. If daily limit of deletes exceeded, API error 906 is returned.
     *
     * @param  \UniOne\Model\SuppressionDeleteRequest $suppressionDeleteRequest suppressionDeleteRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \UniOne\Model\SuccessResponse|\UniOne\Model\ErrorResponse
     */
    public function suppressionDelete(
        \UniOne\Model\SuppressionDeleteRequest $suppressionDeleteRequest,
        string $contentType = self::contentTypes['suppressionDelete'][0]
    ): \UniOne\Model\SuccessResponse|\UniOne\Model\ErrorResponse
    {
        list($response) = $this->suppressionDeleteWithHttpInfo($suppressionDeleteRequest, $contentType);
        return $response;
    }

    /**
     * Operation suppressionDeleteWithHttpInfo
     *
     * Deletes an email from suppression list (only records with is_deletable&#x3D;true). If there are no entries of this email in the suppression list, API error 3003 is returned. If such entries exist but no one can be deleted, API error 3004 is returned. If daily limit of deletes exceeded, API error 906 is returned.
     *
     * @param  \UniOne\Model\SuppressionDeleteRequest $suppressionDeleteRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \UniOne\Model\SuccessResponse|\UniOne\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function suppressionDeleteWithHttpInfo(
        \UniOne\Model\SuppressionDeleteRequest $suppressionDeleteRequest,
        string $contentType = self::contentTypes['suppressionDelete'][0]
    ): array
    {
        $request = $this->suppressionDeleteRequest($suppressionDeleteRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\SuccessResponse',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\UniOne\Model\SuccessResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\SuccessResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation suppressionDeleteAsync
     *
     * Deletes an email from suppression list (only records with is_deletable&#x3D;true). If there are no entries of this email in the suppression list, API error 3003 is returned. If such entries exist but no one can be deleted, API error 3004 is returned. If daily limit of deletes exceeded, API error 906 is returned.
     *
     * @param  \UniOne\Model\SuppressionDeleteRequest $suppressionDeleteRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function suppressionDeleteAsync(
        \UniOne\Model\SuppressionDeleteRequest $suppressionDeleteRequest,
        string $contentType = self::contentTypes['suppressionDelete'][0]
    ): PromiseInterface
    {
        return $this->suppressionDeleteAsyncWithHttpInfo($suppressionDeleteRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation suppressionDeleteAsyncWithHttpInfo
     *
     * Deletes an email from suppression list (only records with is_deletable&#x3D;true). If there are no entries of this email in the suppression list, API error 3003 is returned. If such entries exist but no one can be deleted, API error 3004 is returned. If daily limit of deletes exceeded, API error 906 is returned.
     *
     * @param  \UniOne\Model\SuppressionDeleteRequest $suppressionDeleteRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function suppressionDeleteAsyncWithHttpInfo(
        \UniOne\Model\SuppressionDeleteRequest $suppressionDeleteRequest,
        string $contentType = self::contentTypes['suppressionDelete'][0]
    ): PromiseInterface
    {
        $returnType = '\UniOne\Model\SuccessResponse';
        $request = $this->suppressionDeleteRequest($suppressionDeleteRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'suppressionDelete'
     *
     * @param  \UniOne\Model\SuppressionDeleteRequest $suppressionDeleteRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function suppressionDeleteRequest(
        \UniOne\Model\SuppressionDeleteRequest $suppressionDeleteRequest,
        string $contentType = self::contentTypes['suppressionDelete'][0]
    ): Request
    {

        // verify the required parameter 'suppressionDeleteRequest' is set
        if ($suppressionDeleteRequest === null || (is_array($suppressionDeleteRequest) && count($suppressionDeleteRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $suppressionDeleteRequest when calling suppressionDelete'
            );
        }


        $resourcePath = '/suppression/delete.json';
        $formParams = [];
        $queryParams = [
            'platform' => 'php8-sdk'
        ];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($suppressionDeleteRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($suppressionDeleteRequest));
            } else {
                $httpBody = $suppressionDeleteRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation suppressionGet
     *
     * Gets a reason and date of email suppression.
     *
     * @param  \UniOne\Model\SuppressionGetRequest $suppressionGetRequest suppressionGetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \UniOne\Model\SuppressionGet200Response|\UniOne\Model\ErrorResponse
     */
    public function suppressionGet(
        \UniOne\Model\SuppressionGetRequest $suppressionGetRequest,
        string $contentType = self::contentTypes['suppressionGet'][0]
    ): \UniOne\Model\SuppressionGet200Response|\UniOne\Model\ErrorResponse
    {
        list($response) = $this->suppressionGetWithHttpInfo($suppressionGetRequest, $contentType);
        return $response;
    }

    /**
     * Operation suppressionGetWithHttpInfo
     *
     * Gets a reason and date of email suppression.
     *
     * @param  \UniOne\Model\SuppressionGetRequest $suppressionGetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \UniOne\Model\SuppressionGet200Response|\UniOne\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function suppressionGetWithHttpInfo(
        \UniOne\Model\SuppressionGetRequest $suppressionGetRequest,
        string $contentType = self::contentTypes['suppressionGet'][0]
    ): array
    {
        $request = $this->suppressionGetRequest($suppressionGetRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\SuppressionGet200Response',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\UniOne\Model\SuppressionGet200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\SuppressionGet200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation suppressionGetAsync
     *
     * Gets a reason and date of email suppression.
     *
     * @param  \UniOne\Model\SuppressionGetRequest $suppressionGetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function suppressionGetAsync(
        \UniOne\Model\SuppressionGetRequest $suppressionGetRequest,
        string $contentType = self::contentTypes['suppressionGet'][0]
    ): PromiseInterface
    {
        return $this->suppressionGetAsyncWithHttpInfo($suppressionGetRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation suppressionGetAsyncWithHttpInfo
     *
     * Gets a reason and date of email suppression.
     *
     * @param  \UniOne\Model\SuppressionGetRequest $suppressionGetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function suppressionGetAsyncWithHttpInfo(
        \UniOne\Model\SuppressionGetRequest $suppressionGetRequest,
        string $contentType = self::contentTypes['suppressionGet'][0]
    ): PromiseInterface
    {
        $returnType = '\UniOne\Model\SuppressionGet200Response';
        $request = $this->suppressionGetRequest($suppressionGetRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'suppressionGet'
     *
     * @param  \UniOne\Model\SuppressionGetRequest $suppressionGetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function suppressionGetRequest(
        \UniOne\Model\SuppressionGetRequest $suppressionGetRequest,
        string $contentType = self::contentTypes['suppressionGet'][0]
    ): Request
    {

        // verify the required parameter 'suppressionGetRequest' is set
        if ($suppressionGetRequest === null || (is_array($suppressionGetRequest) && count($suppressionGetRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $suppressionGetRequest when calling suppressionGet'
            );
        }


        $resourcePath = '/suppression/get.json';
        $formParams = [];
        $queryParams = [
            'platform' => 'php8-sdk'
        ];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($suppressionGetRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($suppressionGetRequest));
            } else {
                $httpBody = $suppressionGetRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation suppressionList
     *
     * Returns a suppression list since provided date.
     *
     * @param  \UniOne\Model\SuppressionListRequest $suppressionListRequest suppressionListRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionList'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \UniOne\Model\SuppressionList200Response|\UniOne\Model\ErrorResponse
     */
    public function suppressionList(
        \UniOne\Model\SuppressionListRequest $suppressionListRequest,
        string $contentType = self::contentTypes['suppressionList'][0]
    ): \UniOne\Model\SuppressionList200Response|\UniOne\Model\ErrorResponse
    {
        list($response) = $this->suppressionListWithHttpInfo($suppressionListRequest, $contentType);
        return $response;
    }

    /**
     * Operation suppressionListWithHttpInfo
     *
     * Returns a suppression list since provided date.
     *
     * @param  \UniOne\Model\SuppressionListRequest $suppressionListRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionList'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \UniOne\Model\SuppressionList200Response|\UniOne\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function suppressionListWithHttpInfo(
        \UniOne\Model\SuppressionListRequest $suppressionListRequest,
        string $contentType = self::contentTypes['suppressionList'][0]
    ): array
    {
        $request = $this->suppressionListRequest($suppressionListRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\SuppressionList200Response',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\UniOne\Model\SuppressionList200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\SuppressionList200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation suppressionListAsync
     *
     * Returns a suppression list since provided date.
     *
     * @param  \UniOne\Model\SuppressionListRequest $suppressionListRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionList'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function suppressionListAsync(
        \UniOne\Model\SuppressionListRequest $suppressionListRequest,
        string $contentType = self::contentTypes['suppressionList'][0]
    ): PromiseInterface
    {
        return $this->suppressionListAsyncWithHttpInfo($suppressionListRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation suppressionListAsyncWithHttpInfo
     *
     * Returns a suppression list since provided date.
     *
     * @param  \UniOne\Model\SuppressionListRequest $suppressionListRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionList'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function suppressionListAsyncWithHttpInfo(
        \UniOne\Model\SuppressionListRequest $suppressionListRequest,
        string $contentType = self::contentTypes['suppressionList'][0]
    ): PromiseInterface
    {
        $returnType = '\UniOne\Model\SuppressionList200Response';
        $request = $this->suppressionListRequest($suppressionListRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'suppressionList'
     *
     * @param  \UniOne\Model\SuppressionListRequest $suppressionListRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionList'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function suppressionListRequest(
        \UniOne\Model\SuppressionListRequest $suppressionListRequest,
        string $contentType = self::contentTypes['suppressionList'][0]
    ): Request
    {

        // verify the required parameter 'suppressionListRequest' is set
        if ($suppressionListRequest === null || (is_array($suppressionListRequest) && count($suppressionListRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $suppressionListRequest when calling suppressionList'
            );
        }


        $resourcePath = '/suppression/list.json';
        $formParams = [];
        $queryParams = [
            'platform' => 'php8-sdk'
        ];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($suppressionListRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($suppressionListRequest));
            } else {
                $httpBody = $suppressionListRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation suppressionSet
     *
     * Adds an email address to the suppression list. You can always remove this address from the suppression list later using the [suppression/delete](https://docs.unione.io/en/web-api-ref#suppression-delete) method.
     *
     * @param  \UniOne\Model\SuppressionSetRequest $suppressionSetRequest suppressionSetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionSet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \UniOne\Model\SuccessResponse|\UniOne\Model\ErrorResponse
     */
    public function suppressionSet(
        \UniOne\Model\SuppressionSetRequest $suppressionSetRequest,
        string $contentType = self::contentTypes['suppressionSet'][0]
    ): \UniOne\Model\SuccessResponse|\UniOne\Model\ErrorResponse
    {
        list($response) = $this->suppressionSetWithHttpInfo($suppressionSetRequest, $contentType);
        return $response;
    }

    /**
     * Operation suppressionSetWithHttpInfo
     *
     * Adds an email address to the suppression list. You can always remove this address from the suppression list later using the [suppression/delete](https://docs.unione.io/en/web-api-ref#suppression-delete) method.
     *
     * @param  \UniOne\Model\SuppressionSetRequest $suppressionSetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionSet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \UniOne\Model\SuccessResponse|\UniOne\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function suppressionSetWithHttpInfo(
        \UniOne\Model\SuppressionSetRequest $suppressionSetRequest,
        string $contentType = self::contentTypes['suppressionSet'][0]
    ): array
    {
        $request = $this->suppressionSetRequest($suppressionSetRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\SuccessResponse',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\UniOne\Model\SuccessResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\SuccessResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation suppressionSetAsync
     *
     * Adds an email address to the suppression list. You can always remove this address from the suppression list later using the [suppression/delete](https://docs.unione.io/en/web-api-ref#suppression-delete) method.
     *
     * @param  \UniOne\Model\SuppressionSetRequest $suppressionSetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionSet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function suppressionSetAsync(
        \UniOne\Model\SuppressionSetRequest $suppressionSetRequest,
        string $contentType = self::contentTypes['suppressionSet'][0]
    ): PromiseInterface
    {
        return $this->suppressionSetAsyncWithHttpInfo($suppressionSetRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation suppressionSetAsyncWithHttpInfo
     *
     * Adds an email address to the suppression list. You can always remove this address from the suppression list later using the [suppression/delete](https://docs.unione.io/en/web-api-ref#suppression-delete) method.
     *
     * @param  \UniOne\Model\SuppressionSetRequest $suppressionSetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionSet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function suppressionSetAsyncWithHttpInfo(
        \UniOne\Model\SuppressionSetRequest $suppressionSetRequest,
        string $contentType = self::contentTypes['suppressionSet'][0]
    ): PromiseInterface
    {
        $returnType = '\UniOne\Model\SuccessResponse';
        $request = $this->suppressionSetRequest($suppressionSetRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'suppressionSet'
     *
     * @param  \UniOne\Model\SuppressionSetRequest $suppressionSetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suppressionSet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function suppressionSetRequest(
        \UniOne\Model\SuppressionSetRequest $suppressionSetRequest,
        string $contentType = self::contentTypes['suppressionSet'][0]
    ): Request
    {

        // verify the required parameter 'suppressionSetRequest' is set
        if ($suppressionSetRequest === null || (is_array($suppressionSetRequest) && count($suppressionSetRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $suppressionSetRequest when calling suppressionSet'
            );
        }


        $resourcePath = '/suppression/set.json';
        $formParams = [];
        $queryParams = [
            'platform' => 'php8-sdk'
        ];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($suppressionSetRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($suppressionSetRequest));
            } else {
                $httpBody = $suppressionSetRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
