<?php
/**
 * TemplateApi
 * PHP version 8.1
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.<br>The preferred way is to use https://api.unione.io/en/transactional/api/v1 endpoint, but also you can use https://eu1.unione.io/en/transactional/api/v1 or https://us1.unione.io/en/transactional/api/v1 directly, depending on the host your account was registered at.
 *
 * The version of the OpenAPI document: 1.76
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace UniOne\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use UniOne\ApiException;
use UniOne\Configuration;
use UniOne\HeaderSelector;
use UniOne\FormDataProcessor;
use UniOne\ObjectSerializer;

/**
 * TemplateApi Class Doc Comment
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TemplateApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'templateDelete' => [
            'application/json',
        ],
        'templateGet' => [
            'application/json',
        ],
        'templateList' => [
            'application/json',
        ],
        'templateSet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation templateDelete
     *
     * Deletes a template by id.
     *
     * @param  \UniOne\Model\TemplateGetRequest $templateGetRequest templateGetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \UniOne\Model\SuccessResponse|\UniOne\Model\ErrorResponse
     */
    public function templateDelete(
        \UniOne\Model\TemplateGetRequest $templateGetRequest,
        string $contentType = self::contentTypes['templateDelete'][0]
    ): \UniOne\Model\SuccessResponse|\UniOne\Model\ErrorResponse
    {
        list($response) = $this->templateDeleteWithHttpInfo($templateGetRequest, $contentType);
        return $response;
    }

    /**
     * Operation templateDeleteWithHttpInfo
     *
     * Deletes a template by id.
     *
     * @param  \UniOne\Model\TemplateGetRequest $templateGetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \UniOne\Model\SuccessResponse|\UniOne\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function templateDeleteWithHttpInfo(
        \UniOne\Model\TemplateGetRequest $templateGetRequest,
        string $contentType = self::contentTypes['templateDelete'][0]
    ): array
    {
        $request = $this->templateDeleteRequest($templateGetRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\SuccessResponse',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\UniOne\Model\SuccessResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\SuccessResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation templateDeleteAsync
     *
     * Deletes a template by id.
     *
     * @param  \UniOne\Model\TemplateGetRequest $templateGetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function templateDeleteAsync(
        \UniOne\Model\TemplateGetRequest $templateGetRequest,
        string $contentType = self::contentTypes['templateDelete'][0]
    ): PromiseInterface
    {
        return $this->templateDeleteAsyncWithHttpInfo($templateGetRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation templateDeleteAsyncWithHttpInfo
     *
     * Deletes a template by id.
     *
     * @param  \UniOne\Model\TemplateGetRequest $templateGetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function templateDeleteAsyncWithHttpInfo(
        \UniOne\Model\TemplateGetRequest $templateGetRequest,
        string $contentType = self::contentTypes['templateDelete'][0]
    ): PromiseInterface
    {
        $returnType = '\UniOne\Model\SuccessResponse';
        $request = $this->templateDeleteRequest($templateGetRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'templateDelete'
     *
     * @param  \UniOne\Model\TemplateGetRequest $templateGetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function templateDeleteRequest(
        \UniOne\Model\TemplateGetRequest $templateGetRequest,
        string $contentType = self::contentTypes['templateDelete'][0]
    ): Request
    {

        // verify the required parameter 'templateGetRequest' is set
        if ($templateGetRequest === null || (is_array($templateGetRequest) && count($templateGetRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $templateGetRequest when calling templateDelete'
            );
        }


        $resourcePath = '/template/delete.json';
        $formParams = [];
        $queryParams = [
            'platform' => 'php8-sdk'
        ];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($templateGetRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($templateGetRequest));
            } else {
                $httpBody = $templateGetRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation templateGet
     *
     * Gets template properties by it&#39;s id.
     *
     * @param  \UniOne\Model\TemplateGetRequest $templateGetRequest templateGetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \UniOne\Model\TemplateSet200Response|\UniOne\Model\ErrorResponse
     */
    public function templateGet(
        \UniOne\Model\TemplateGetRequest $templateGetRequest,
        string $contentType = self::contentTypes['templateGet'][0]
    ): \UniOne\Model\TemplateSet200Response|\UniOne\Model\ErrorResponse
    {
        list($response) = $this->templateGetWithHttpInfo($templateGetRequest, $contentType);
        return $response;
    }

    /**
     * Operation templateGetWithHttpInfo
     *
     * Gets template properties by it&#39;s id.
     *
     * @param  \UniOne\Model\TemplateGetRequest $templateGetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \UniOne\Model\TemplateSet200Response|\UniOne\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function templateGetWithHttpInfo(
        \UniOne\Model\TemplateGetRequest $templateGetRequest,
        string $contentType = self::contentTypes['templateGet'][0]
    ): array
    {
        $request = $this->templateGetRequest($templateGetRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\TemplateSet200Response',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\UniOne\Model\TemplateSet200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\TemplateSet200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation templateGetAsync
     *
     * Gets template properties by it&#39;s id.
     *
     * @param  \UniOne\Model\TemplateGetRequest $templateGetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function templateGetAsync(
        \UniOne\Model\TemplateGetRequest $templateGetRequest,
        string $contentType = self::contentTypes['templateGet'][0]
    ): PromiseInterface
    {
        return $this->templateGetAsyncWithHttpInfo($templateGetRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation templateGetAsyncWithHttpInfo
     *
     * Gets template properties by it&#39;s id.
     *
     * @param  \UniOne\Model\TemplateGetRequest $templateGetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function templateGetAsyncWithHttpInfo(
        \UniOne\Model\TemplateGetRequest $templateGetRequest,
        string $contentType = self::contentTypes['templateGet'][0]
    ): PromiseInterface
    {
        $returnType = '\UniOne\Model\TemplateSet200Response';
        $request = $this->templateGetRequest($templateGetRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'templateGet'
     *
     * @param  \UniOne\Model\TemplateGetRequest $templateGetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function templateGetRequest(
        \UniOne\Model\TemplateGetRequest $templateGetRequest,
        string $contentType = self::contentTypes['templateGet'][0]
    ): Request
    {

        // verify the required parameter 'templateGetRequest' is set
        if ($templateGetRequest === null || (is_array($templateGetRequest) && count($templateGetRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $templateGetRequest when calling templateGet'
            );
        }


        $resourcePath = '/template/get.json';
        $formParams = [];
        $queryParams = [
            'platform' => 'php8-sdk'
        ];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($templateGetRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($templateGetRequest));
            } else {
                $httpBody = $templateGetRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation templateList
     *
     * Returns the list of all or some templates of the account.
     *
     * @param  \UniOne\Model\TemplateListRequest $templateListRequest templateListRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateList'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \UniOne\Model\TemplateList200Response|\UniOne\Model\ErrorResponse
     */
    public function templateList(
        \UniOne\Model\TemplateListRequest $templateListRequest,
        string $contentType = self::contentTypes['templateList'][0]
    ): \UniOne\Model\TemplateList200Response|\UniOne\Model\ErrorResponse
    {
        list($response) = $this->templateListWithHttpInfo($templateListRequest, $contentType);
        return $response;
    }

    /**
     * Operation templateListWithHttpInfo
     *
     * Returns the list of all or some templates of the account.
     *
     * @param  \UniOne\Model\TemplateListRequest $templateListRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateList'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \UniOne\Model\TemplateList200Response|\UniOne\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function templateListWithHttpInfo(
        \UniOne\Model\TemplateListRequest $templateListRequest,
        string $contentType = self::contentTypes['templateList'][0]
    ): array
    {
        $request = $this->templateListRequest($templateListRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\TemplateList200Response',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\UniOne\Model\TemplateList200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\TemplateList200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation templateListAsync
     *
     * Returns the list of all or some templates of the account.
     *
     * @param  \UniOne\Model\TemplateListRequest $templateListRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateList'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function templateListAsync(
        \UniOne\Model\TemplateListRequest $templateListRequest,
        string $contentType = self::contentTypes['templateList'][0]
    ): PromiseInterface
    {
        return $this->templateListAsyncWithHttpInfo($templateListRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation templateListAsyncWithHttpInfo
     *
     * Returns the list of all or some templates of the account.
     *
     * @param  \UniOne\Model\TemplateListRequest $templateListRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateList'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function templateListAsyncWithHttpInfo(
        \UniOne\Model\TemplateListRequest $templateListRequest,
        string $contentType = self::contentTypes['templateList'][0]
    ): PromiseInterface
    {
        $returnType = '\UniOne\Model\TemplateList200Response';
        $request = $this->templateListRequest($templateListRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'templateList'
     *
     * @param  \UniOne\Model\TemplateListRequest $templateListRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateList'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function templateListRequest(
        \UniOne\Model\TemplateListRequest $templateListRequest,
        string $contentType = self::contentTypes['templateList'][0]
    ): Request
    {

        // verify the required parameter 'templateListRequest' is set
        if ($templateListRequest === null || (is_array($templateListRequest) && count($templateListRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $templateListRequest when calling templateList'
            );
        }


        $resourcePath = '/template/list.json';
        $formParams = [];
        $queryParams = [
            'platform' => 'php8-sdk'
        ];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($templateListRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($templateListRequest));
            } else {
                $httpBody = $templateListRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation templateSet
     *
     * Creates or updates an email template.
     *
     * @param  \UniOne\Model\TemplateSetRequest $templateSetRequest templateSetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateSet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \UniOne\Model\TemplateSet200Response|\UniOne\Model\ErrorResponse
     */
    public function templateSet(
        \UniOne\Model\TemplateSetRequest $templateSetRequest,
        string $contentType = self::contentTypes['templateSet'][0]
    ): \UniOne\Model\TemplateSet200Response|\UniOne\Model\ErrorResponse
    {
        list($response) = $this->templateSetWithHttpInfo($templateSetRequest, $contentType);
        return $response;
    }

    /**
     * Operation templateSetWithHttpInfo
     *
     * Creates or updates an email template.
     *
     * @param  \UniOne\Model\TemplateSetRequest $templateSetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateSet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \UniOne\Model\TemplateSet200Response|\UniOne\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function templateSetWithHttpInfo(
        \UniOne\Model\TemplateSetRequest $templateSetRequest,
        string $contentType = self::contentTypes['templateSet'][0]
    ): array
    {
        $request = $this->templateSetRequest($templateSetRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\TemplateSet200Response',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\UniOne\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\UniOne\Model\TemplateSet200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\TemplateSet200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\UniOne\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation templateSetAsync
     *
     * Creates or updates an email template.
     *
     * @param  \UniOne\Model\TemplateSetRequest $templateSetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateSet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function templateSetAsync(
        \UniOne\Model\TemplateSetRequest $templateSetRequest,
        string $contentType = self::contentTypes['templateSet'][0]
    ): PromiseInterface
    {
        return $this->templateSetAsyncWithHttpInfo($templateSetRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation templateSetAsyncWithHttpInfo
     *
     * Creates or updates an email template.
     *
     * @param  \UniOne\Model\TemplateSetRequest $templateSetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateSet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function templateSetAsyncWithHttpInfo(
        \UniOne\Model\TemplateSetRequest $templateSetRequest,
        string $contentType = self::contentTypes['templateSet'][0]
    ): PromiseInterface
    {
        $returnType = '\UniOne\Model\TemplateSet200Response';
        $request = $this->templateSetRequest($templateSetRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'templateSet'
     *
     * @param  \UniOne\Model\TemplateSetRequest $templateSetRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['templateSet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function templateSetRequest(
        \UniOne\Model\TemplateSetRequest $templateSetRequest,
        string $contentType = self::contentTypes['templateSet'][0]
    ): Request
    {

        // verify the required parameter 'templateSetRequest' is set
        if ($templateSetRequest === null || (is_array($templateSetRequest) && count($templateSetRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $templateSetRequest when calling templateSet'
            );
        }


        $resourcePath = '/template/set.json';
        $formParams = [];
        $queryParams = [
            'platform' => 'php8-sdk'
        ];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($templateSetRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($templateSetRequest));
            } else {
                $httpBody = $templateSetRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
