<?php
/**
 * WebhookSetJsonPostRequestEventsByUserInnerEventsInnerEventDataDeliveryInfoTest
 *
 * PHP version 8.1
 *
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.<br>You can use https://eu1.unione.io/en/transactional/api/v1 or https://us1.unione.io/en/transactional/api/v1 directly.
 *
 * The version of the OpenAPI document: 1.76
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace UniOne\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WebhookSetJsonPostRequestEventsByUserInnerEventsInnerEventDataDeliveryInfoTest Class Doc Comment
 *
 * @description Object with detailed delivery info.Event date &amp; time in UTC time zone in **YYYY-MM-DD hh:mm:ss** format. This property exists only if webhook has delivery_info proeprty set to 1 and event_name&#x3D;**transactional_email_status**.
 * @package     UniOne
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WebhookSetJsonPostRequestEventsByUserInnerEventsInnerEventDataDeliveryInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WebhookSetJsonPostRequestEventsByUserInnerEventsInnerEventDataDeliveryInfo"
     */
    public function testWebhookSetJsonPostRequestEventsByUserInnerEventsInnerEventDataDeliveryInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "deliveryStatus"
     */
    public function testPropertyDeliveryStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "destinationResponse"
     */
    public function testPropertyDestinationResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "userAgent"
     */
    public function testPropertyUserAgent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
